fix_r = physics_fixture_create()
physics_fixture_set_polygon_shape(fix_r)
physics_fixture_add_point(fix_r,0,4)
physics_fixture_add_point(fix_r,57,0)
physics_fixture_add_point(fix_r,75,4)
physics_fixture_add_point(fix_r,80,7)
physics_fixture_add_point(fix_r,80,9)
physics_fixture_add_point(fix_r,75,12)
physics_fixture_add_point(fix_r,57,16)
physics_fixture_add_point(fix_r,0,12)
fix_bind = physics_fixture_bind(fix_r,id)

physics_fixture_set_density(fix_r,0.5)
physics_fixture_set_restitution(fix_r,0.1)
physics_fixture_set_collision_group(fix_r,0)
physics_fixture_set_linear_damping(fix_r,0.1)
physics_fixture_set_angular_damping(fix_r,0.1)
physics_fixture_set_friction(fix_r,0.2)
physics_fixture_set_sensor(fix_r,true)

fix_l = physics_fixture_create()
physics_fixture_set_polygon_shape(fix_l)
physics_fixture_add_point(fix_l,0,4)
physics_fixture_add_point(fix_l,0,12)
physics_fixture_add_point(fix_l,-57,16)
physics_fixture_add_point(fix_l,-75,12)
physics_fixture_add_point(fix_l,-80,9)
physics_fixture_add_point(fix_l,-80,7)
physics_fixture_add_point(fix_l,-75,4)
physics_fixture_add_point(fix_l,-57,0)

physics_fixture_set_density(fix_l,0.5)
physics_fixture_set_restitution(fix_l,0.1)
physics_fixture_set_collision_group(fix_l,0)
physics_fixture_set_linear_damping(fix_l,0.1)
physics_fixture_set_angular_damping(fix_l,0.1)
physics_fixture_set_friction(fix_l,0.2)
physics_fixture_set_sensor(fix_l,true)