fix_r = physics_fixture_create()
physics_fixture_set_polygon_shape(fix_r)
physics_fixture_add_point(fix_r,0,5)
physics_fixture_add_point(fix_r,13,1)
physics_fixture_add_point(fix_r,55,2)
physics_fixture_add_point(fix_r,60,5)
physics_fixture_add_point(fix_r,60,7)
physics_fixture_add_point(fix_r,55,10)
physics_fixture_add_point(fix_r,13,11)
physics_fixture_add_point(fix_r,0,7)
fix_bind = physics_fixture_bind(fix_r,id)

physics_fixture_set_density(fix_r,0.5)
physics_fixture_set_restitution(fix_r,0.1)
physics_fixture_set_collision_group(fix_r,0)
physics_fixture_set_linear_damping(fix_r,0.1)
physics_fixture_set_angular_damping(fix_r,0.1)
physics_fixture_set_friction(fix_r,0.2)
physics_fixture_set_sensor(fix_r,true)

fix_l = physics_fixture_create()
physics_fixture_set_polygon_shape(fix_l)
physics_fixture_add_point(fix_l,0,5)
physics_fixture_add_point(fix_l,0,7)
physics_fixture_add_point(fix_l,-13,11)
physics_fixture_add_point(fix_l,-55,10)
physics_fixture_add_point(fix_l,-60,7)
physics_fixture_add_point(fix_l,-60,5)
physics_fixture_add_point(fix_l,-55,2)
physics_fixture_add_point(fix_l,-13,1)

physics_fixture_set_density(fix_l,0.5)
physics_fixture_set_restitution(fix_l,0.1)
physics_fixture_set_collision_group(fix_l,0)
physics_fixture_set_linear_damping(fix_l,0.1)
physics_fixture_set_angular_damping(fix_l,0.1)
physics_fixture_set_friction(fix_l,0.2)
physics_fixture_set_sensor(fix_l,true)